version: "3.1"
services: 
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
  adminer:
    image: adham/website
    restart: always
    links:
      - db
    ports:
      - 8000:8000